select age from public."Customer";

--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from public."Customer"
group by gender
--Male customers bring more revenue compared to female customers, need to do promotion to bring more female customers

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount 
from public."Customer" 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from public."Customer")


-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating"
from public."Customer"
group by item_purchased
order by avg(review_rating) desc
limit 5

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, 
ROUND(avg(purchase_amount),2)
from public."Customer"
where shipping_type in ('Standard','Express')
group by shipping_type;
--On average people used Express Shipping more than Standard, the business should focus on more on faster shipping methods.

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM public."Customer"
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;
--People with no subscription brin more revenue than subscribed customers, need to some promotion of the subscribtion method like offering 10% off by being a subscriber.

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_applied_rate
FROM public."Customer"
GROUP BY item_purchased
ORDER BY discount_applied_rate DESC
LIMIT 5;
--

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM public."Customer")

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;
--there are a very few "New coustomers", business should start doing advertisement to bring more customers.

--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM public."Customer"
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
 
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM public."Customer"
WHERE previous_purchases > 5
GROUP BY subscription_status;
---Majority of the repeat customers are not subscribers, need to offer them some kind of incentives to subcribe.

--Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM public."Customer"
GROUP BY age_group
ORDER BY total_revenue desc;
--yound Adults brint majority of revenue from all the age group, need to look into how to attract more senior people.

